USE db;

CREATE TABLE WorkTable (
id INTEGER NOT NULL AUTO_INCREMENT,
date DATETIME NOT NULL,
title VARCHAR(30) NOT NULL,
artist VARCHAR(30) NOT NULL,
likes INTEGER NOT NULL,
description VARCHAR(400),
PRIMARY KEY (id)
);