version: "3"
services:
  app:
    ports:
      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    networks:
      - network1

  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
    networks:
      - network1

networks:
  network1: